apiVersion: v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    app: customer
  name: customer
spec:
  replicas: 1
  selector:
    app: customer
    deploymentconfig: customer
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: customer
        deploymentconfig: customer
    spec:
      containers:
      - args:
        - --bind
        - 0.0.0.0
        - --port
        - '8080'
        - customer
        command:
        - hotrod
        image: " "
        imagePullPolicy: Always
        name: customer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - customer
      from:
        kind: ImageStreamTag
        name: customer:latest
        namespace: tracer
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
