kind: Service
apiVersion: v1
metadata:
  name: driver
spec:
  selector:
    app: driver
    deploymentconfig: driver
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30061
  type: LoadBalancer
